version: 0.2
phases:
  build:
    commands:
    - mvn clean install
  post_build:
    commands:
    - mv target/Spyglass-backend-0.0.1-SNAPSHOT.jar Spyglass-backend-0.0.1-SNAPSHOT.jar
artifacts:
  files:
  - Spyglass-backend-0.0.1-SNAPSHOT.jar