my:
  env:
    mode: DEV
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD_DEV}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 283938601550-gvvho1452ajpjlg0528cr408v8suff33.apps.googleusercontent.com
            client-secret: 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
frontend-url: http://localhost:5173
aws:
  accessKey: ${{ secrets.S3_IMAGE_ACCESS_KEY }}
  secretKey: ${{ secrets.S3_IMAGE_SECRET_KEY }}
  region: us-east-1
  bucket:
    name: kiruthika-project3-bucket