my:
  env:
    mode: PROD
spring:
  datasource:
    url: jdbc:postgresql://kiruthika-spyglass-db.cluster-c4eqo06kg56i.us-east-1.rds.amazonaws.com:5432/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD_PROD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
frontend-url: http://kiruthika-project3-spyglass.s3-website-us-east-1.amazonaws.com
aws:
  accessKey: ${S3_IMAGE_ACCESS_KEY}
  secretKey: ${S3_IMAGE_SECRET_KEY}
  region: us-east-1
  bucket:
    name: kiruthika-project3-bucket