my:
  env:
    mode: DEV
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD_DEV}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
frontend-url: http://localhost:5173
aws:
  access-key: ${S3_IMAGE_ACCESS_KEY}
  secret-key: ${S3_IMAGE_SECRET_KEY}
  region: us-east-1
  bucket:
    name: kiruthika-project3-bucket